name: Build & Deploy Stream Overlay to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Go (needed by build.sh)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      # 3. Ensure build.sh is executable
      - name: Make build script executable
        run: chmod +x ./build.sh

      # 4. Run your build.sh to produce the build/ folder
      - name: Run build.sh
        run: |
          ./build.sh

      # 5. Sync the build folder to S3
      - name: Upload build/ to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: david-portfolio-site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: "./build"
