name: Build & Deploy Stream Overlay to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Go (required by build.sh)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      # 3. Make build.sh executable
      - name: Make build script executable
        run: chmod +x ./build.sh

      # 4. Run build.sh to produce the build/ directory
      - name: Build stream-overlay
        run: ./build.sh

      # 5. Deploy static site and binary to S3
      - name: Deploy to S3
        env:
          AWS_S3_BUCKET: david-portfolio-site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Sync your web assets to the bucket root (index.html, panel.html, etc.)
          aws s3 sync build/stream-overlay-web/ s3://$AWS_S3_BUCKET/ --acl public-read --delete

          # Upload your Go binary into a bin/ folder
          aws s3 cp build/stream-overlay-server s3://$AWS_S3_BUCKET/bin/stream-overlay-server --acl public-read
